spring.config.import: classpath:/default.yaml
--- ##override params below
spring:
  datasource:
    username: booking
    password: password
    url: jdbc:postgresql://10.10.10.10:5432/pre_order_booking

server:
  port: 9090
