server:
  port: '8080'
  servlet:
    contextPath: /pre-orderBooking

#hibernate:
 # dialect: org.hibernate.dialect.PostgreSQLDialect
  #show_sql: 'false'
spring.banner.location : classpath:app-banner

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
    url: jdbc:postgresql://10.10.10.10:5432/orderBooking
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
